package com.mizu.mizuapi.ws;

public enum SchoolType {
    UNIVERSITY, POLYTECHNIC,
    ACADEMIES_ORDINARY, ACADEMIES_MARINE, ACADEMIES_THEATER, ACADEMIES_MUSIC, ACADEMIES_MEDICAL,
    ACADEMIES_PHYSICAL_EDUCATION, ACADEMIES_FINE_ARTS, ACADEMIES_PEDAGOGICAL,
    UNIVERSITY_MEDICAL, UNIVERSITY_AGRICULTURAL, UNIVERSITY_PEDAGOGICAL, UNIVERSITY_ECONOMIC,
    UNIVERSITY_MILITARY, UNIVERSITY_THEOLOGICAL
}
