export enum SchoolType {
    UNIVERSITY = 'UNIVERSITY',
    POLYTECHNIC = 'POLYTECHNIC',
    ACADEMIES_ORDINARY = 'ACADEMEIS_ORDINARY',
    ACADEMIES_MARINE = 'ACADEMIES_MARINE',
    ACADEMIES_THEATER = 'ACADEMIES_THEATER',
    ACADEMIES_MUSIC = 'ACADEMIES_MUSIC', 
    ACADEMIES_MEDICAL = 'ACADEMIES_MEDICAL',
    ACADEMIES_PHYSICAL_EDUCATION = 'ACADEMIES_PHYSICAL_EDUCATION', 
    ACADEMIES_FINE_ARTS = 'ACADEMIES_FINE_ARTS',
    ACADEMIES_PEDAGOGICAL = 'ACADEMIES_PEDAGOGICAL',
    UNIVERSITY_PEDAGOGICAL = 'UNIVERSITY_PEDAGOGICAL',
    UNIVERSITY_MEDICAL = 'ACADEMIES_MEDICAL', 
    UNIVERSITY_AGRICULTURAL = 'ACADEMIES_AGRICULTURAL',
    UNIVERSITY_ECONOMIC = 'ACADEMIES_ECONOMIC',
    UNIVERSITY_MILITARY = 'ACADEMIES_MILITARY', 
    UNIVERSITY_THEOLOGICAL = 'ACADEMIES_THEOLOGICAL',
}
  